import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import DifyChatbot from './bot';
import OffcanvasExample from '@/components/Navbar';
import Footer from '@/components/Footer';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className='pageContainer'>
          <OffcanvasExample />
        <main className='content'>
          {children}
        </main>
        <Footer />
        <DifyChatbot />
      </body>
    </html>
  );
}
