import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import DifyChatbot from './bot';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        {children}
        <DifyChatbot />
      </body>
    </html>
  );
}
